<template>
    <div class="policies-wrapper fx jc-c">
        <div class="policies-holder">
            <h1>Privacy policy</h1>
            <h4>Terms and Conditions (“Terms”)</h4>
            <h4 class="gray">Last updated: June 20, 2022</h4>
            <div class="p-section">
                <p>
                    This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <router-link to="/terms-and-conditions">flexsale.com/terms-and-conditions</router-link>
                </p>
            </div>
            <div class="p-section">
                <h2>Definitions</h2>
                <div class="p-section-sub">
                    <h3>Service</h3>
                    <p>
                        Service is the websites and applications operated by Flexsale.com
                    </p>
                </div>
                <div class="p-section-sub">
                    <h3>Personal Data</h3>
                    <p>
                        Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </p>
                </div>
                <div class="p-section-sub">
                    <h3>Usage Data</h3>
                    <p>
                        Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </p>
                </div>
                <div class="p-section-sub">
                    <h3>Cookies</h3>
                    <p>
                        Cookies are small files stored on your device (computer or mobile device).
                    </p>
                </div>
            </div>
            <div class="p-section">
                <h2>
                    Information Collection and Use
                </h2>
                <p>
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>
            </div>
            <div class="p-section">
                <h2>
                    Types of Data Collected
                </h2>
                <p>
                    The various types of data we collect on users are categorized into the following;
                </p>
                <div class="p-section-sub">
                    <h3>Personal Data</h3>
                    <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
                    <ul>
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Address, State, Province, ZIP/Postal code, City</li>
                        <li>Cookies and Usage Data</li>
                    </ul>
                </div>
                <div class="p-section-sub">
                    <h3>Usage Data</h3>
                    <p>
                        We may also collect information how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    </p>
                </div>
                <div class="p-section-sub">
                    <h3>Tracking Cookies Data</h3>
                    <p>
                        We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                    </p>
                    <p>
                        Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
                    </p>
                    <p>
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                    </p>
                    <div class="mini-list">
                        <p>
                            Examples of Cookies we use:
                        </p>
                        <ul>
                            <li><strong>Session Cookies.</strong>We use Session Cookies to operate our Service.</li>
                            <li><strong>Preference Cookies.</strong>We use Preference Cookies to remember your preferences and various settings.</li>
                            <li><strong>Security Cookies.</strong>We use Security Cookies for security purposes.</li>
                        </ul>
                        <p>Read more about our <router-link to="/cookies-policy">cookie policy.</router-link></p>
                    </div>
                </div>
            </div>
            <div class="p-section">
                <h2>Use of Data</h2>
                <p>Flexsale.com  uses the collected data for various purposes:</p>
                <ul>
                    <li>To provide and maintain the Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                    <li>To provide customer care and support</li>
                    <li>To provide analysis or valuable information so that we can improve the Service</li>
                    <li>To monitor the usage of the Service</li>
                    <li>To detect, prevent and address technical issues</li>
                </ul>
            </div>
            <div class="p-section">
                <h2>Transfer of Data</h2>
                <p>
                    Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                </p>
                <p>
                    If you are located outside Ghana and choose to provide information to us, please note that we transfer the data, including Personal Data, to Ghana and process it there.
                </p>
                <p>
                    Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
                <p>
                    Flexsale.com will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>
            </div>
            <div class="p-section">
                <h2>
                    Disclosure of Data
                </h2>
                <div class="p-section-sub">
                    <h3>Legal Requirements</h3>
                    <p>
                        Flexsale.com may disclose your Personal Data in the good faith belief that such action is necessary to:
                    </p>
                    <ul>
                        <li>To comply with a legal obligation</li>
                        <li>To protect and defend the rights or property of <strong>flexsale.com</strong></li>
                        <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                        <li>To protect the personal safety of users of the Service or the public</li>
                        <li>To protect against legal liability</li>
                    </ul>
                </div>
            </div>
            <div class="p-section">
                <h2>Links to Other Sites</h2>
                <p>
                    Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
                <p>
                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
            </div>
            <div class="p-section">
                <h2>Children’s Privacy</h2>
                <p>
                    Our Service does not address anyone under the age of 18 (“Children”).
                </p>
                <p>
                    We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our database. 
                </p>
            </div>
            <div class="p-section">
                <h2>
                    Changes to This Privacy Policy
                </h2>
                <p>
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
            </div>
            <div class="p-section">
                <h2>
                    <strong>Contact Us</strong>
                </h2>
                <p>If you have any questions about these Policies, please <router-link to="/">contact us.</router-link></p>
            </div>
        </div>
    </div>
</template>
<script>
import scrollTopMixin from '../mixins/scrollTopMixin'
export default {
    name: 'PrivacyPolicy',
    mixins: [scrollTopMixin]
}
</script>
<style lang="scss" scoped>

</style>